### PR TITLE
added stellar sdk to local js location

### PR DESCRIPTION
**Pull request by codehakase**
update http handler on stellar-admin to use wp_* directives

### CODE REVIEW

**Comment by codehakase** [comment]
Will update once full updates are reflected

**Comment by flarcos** [comment]
> Will update once full updates are reflected

noted

**Comment by codehakase** [comment]
@slideloft update complete!

**Comment by flarcos** [comment]
bug noticed at checkout https://swplug.com/word/checkout/ 
timer restarts after countdown end , 
process is as following :1, User click Get memo==> 2,count down timer begins based on time set by admin ( in this case 120 seconds) ==> 3,after timer reaches 0 , it checks for payment with the memo provided .==> after checking if memo is available on ledger it process payment to pending, if not available it provides a pop up of payment not made.

The bug is at step 2 as it is not checking for payment and countdown keeps recurring

**Comment by flarcos** [comment]
for a working version without bug from previous build check https://swplug.com/store/

**Comment by codehakase** [comment]
Can you confirm if there are any console error logs that can depict this?

**Comment by flarcos** [comment]
Screenshot 2019-06-06 at 14 22 54

**Comment by flarcos** [comment]
GET https://swplug.com/word/wp-content/plugins/swplug-plus/public/partials/js/stellar-sdk.js?ver=5.2.1 404 (Not Found)

**Comment by flarcos** [comment]
full data from console : 

`VM524:15 Mixed Content: The page at 'https://swplug.com/word/checkout/' was loaded over HTTPS, but requested an insecure script 'http://swplug.com/word/wp-includes/js/wp-emoji-release.min.js?ver=5.2.1'. This content should also be served over HTTPS.
f @ VM524:15
(anonymous) @ VM524:15
(anonymous) @ VM524:15
jquery-migrate.min.js?ver=1.4.1:2 JQMIGRATE: Migrate is installed, version 1.4.1
(index):1 Mixed Content: The page at 'https://swplug.com/word/checkout/' was loaded over HTTPS, but requested an insecure script 'http://swplug.com/word/wp-content/plugins/swplug-plus/public/partials/js/stellar-sdk.js?ver=5.2.1'. This content should also be served over HTTPS.
(index):1038 GET https://swplug.com/word/wp-content/plugins/swplug-plus/public/partials/js/stellar-sdk.js?ver=5.2.1 404 (Not Found)
(index):1 Mixed Content: The page at 'https://swplug.com/word/checkout/' was loaded over HTTPS, but requested an insecure image 'http://swplug.com/word/wp-content/plugins/swplug-plus/images/XLM.png'. This content should also be served over HTTPS.
jquery.js?ver=1.12.4-wp:4 Mixed Content: The page at 'https://swplug.com/word/checkout/' was loaded over HTTPS, but requested an insecure image 'http://swplug.com/word/wp-content/plugins/swplug-plus/images/XLM.png'. This content should also be served over HTTPS.`

**Comment by flarcos** [comment]
one more. can you make sure content from the plugin load via https . note : This content should also be served over HTTPS

**Comment by codehakase** [comment]
@slideloft retry tests again!

**Comment by flarcos** [comment]
Works , i will merge and submit to wordpress for further feedback

**Pull request merged**
